# Generated by Django 2.2.3 on 2019-08-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitems',
            name='content',
        ),
        migrations.AddField(
            model_name='listitems',
            name='listitems',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
