# Generated by Django 2.2.3 on 2019-08-13 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MomoRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_text', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=1, max_digits=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Collectionrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_text', models.CharField(max_length=240)),
                ('votes', models.IntegerField(default=0)),
                ('collection_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='momo.MomoRequest')),
            ],
        ),
    ]
