# Generated by Django 2.2.3 on 2019-08-13 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MomoRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_text', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=1, max_digits=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('account_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CollectionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_request', models.BooleanField(default=True)),
                ('poll', models.IntegerField(default=0)),
                ('momo_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='momo.MomoRequest')),
            ],
        ),
    ]
