# Generated by Django 2.2.3 on 2019-08-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.RemoveField(
            model_name='collectionrequest',
            name='collection_text',
        ),
        migrations.AddField(
            model_name='collectionrequest',
            name='collection',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='momorequest',
            name='collection',
            field=models.BooleanField(default=True),
        ),
    ]
