# Generated by Django 2.2.3 on 2019-08-13 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('momo', '0003_auto_20190813_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionrequest',
            name='request_payment',
        ),
        migrations.RemoveField(
            model_name='momorequest',
            name='collection',
        ),
        migrations.AddField(
            model_name='collectionrequest',
            name='momo_request',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='momo.MomoRequest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collectionrequest',
            name='collection_request',
            field=models.BooleanField(default=True),
        ),
    ]
