# Generated by Django 2.2.3 on 2019-08-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('momo', '0004_auto_20190813_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionrequest',
            old_name='votes',
            new_name='poll',
        ),
    ]
