# Generated by Django 2.2.3 on 2019-08-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momo', '0005_auto_20190813_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_account',
            name='username',
            field=models.CharField(default=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
